name: example
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  flutter_hooks: ^0.13.0

  redux: ^4.0.0+2
  flutter_redux_hooks: ^0.1.1
  redux_toolkit:
    path: ..
  json_annotation: ^3.0.1
  yaml: ^2.2.1

  cupertino_icons: ^0.1.3
  functional_widget_annotation: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  functional_widget: ^0.8.0
  json_serializable: ^3.2.0

dependency_overrides:
  analyzer: '0.39.14'

flutter:
  uses-material-design: true
  assets:
    - environment.yaml

